pipeline {
    agent any
    parameters {
        string(name: 'ENVIRONMENT', defaultValue: 'QA', description:'')
        string(name: 'PROCESS', defaultValue: 'loadMaster', description:'')
    }
    stages {
        stage('Init') {
            steps {
                echo "Init ${params.ENVIRONMENT}"
            }
        }

        stage('Continue') {
            steps {
                echo 'Continue'
            }
        }

        stage('End') {
            steps {
                echo 'End'
            }
        }

        stage('Deploy Prod') {
            input {
                message "¿despelgar en prod?"
                ok "si"
                parameters {
                    string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
                }
            }
            steps {
                echo "${PERSON} esta desplegando en PROD"
            }
        }


    }
}