pipeline {
    agent any
    parameters {
        string(name: 'ENVIRONMENT', defaultValue: 'QA', descrption:'')
    }
    stages {
        stage('Init') {
            steps {
                echo "Init ${params.ENVIRONMENT}"
            }
        }

        stage('Continue') {
            steps {
                echo 'Continue'
            }
        }

        stage('End') {
            steps {
                echo 'End'
            }
        }
    }
}